### ISSUE TITLE
Typscript Build tab in project properties

### ISSUE THREAD

**Issue by srivatsn** [aspnet/Tooling#1007]
_From @deastr on March 1, 2017 10:42_

I'm not sure if this is the correct place to ask about this, if not please let me know.

There was a TypeScript Build tab in project properties in VS.NET 2015 (with addions to csproj file) but not in VS.NET 2017 RC4. Is there a plan to add this?

_Copied from original issue: dotnet/roslyn-project-system#1661_

**Comment by mlorbetske** [comment]
@paulvanbrenk should this be moved to https://github.com/Microsoft/TypeScript?

**Comment by mlorbetske** [comment]
On the latest preview of Visual Studio 2017.3, I'm seeing the TypeScript Build tab in the project properties, closing this since it appears to be fixed. If you're still seeing that it's not there, please report the issue on the [developer community](https://developercommunity.visualstudio.com/) site
