### ISSUE TITLE
Is no more Application Insight local SDK a thing ?

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#1019]
So no more `local SDK only`, is this now an azure-only service ?

If it's not, then the UI on 2017 is really crafted by evil azure $ eaters. (just kidding, no offense intended)

Also the docs points to the old UI, showing an option not available on 2017.
![pasted image at 2017_03_16 10_22 am](https://cloud.githubusercontent.com/assets/3386797/23998162/fb45dee2-0a32-11e7-85c1-cea08fe44d9b.png)

As an Azure customer that uses app insights already, can you please clarify the situation and if there's a change on how this services is/was used/consumed, can you point to the announcement about it? 

Thanks.

**Comment by mlorbetske** [comment]
This issue was moved to Microsoft/ApplicationInsights-Home#114

**Comment by gardnerjr** [comment]
@Bartmax  where are you not seing this in 2017?  If you created an asp.net or asp.net core project in VS2017, the asp.net tooling *already includes AI in local only mode* right from project creation.

so this link doesn't appear in the configure window, because *AI is already in local mode* in those projects.  The link only appears if you're adding AI to a completely clean project that doesn't already have AI in it.

If this is not what you're seeing, let me know.

**Comment by gardnerjr** [comment]
To see the link in 2017, create a new asp.net or asp.net core project, and remove the references to AI  (in core, open the csproj and remove the `PackageReference` for Application Insights.  Right click the project, and the Application Insights submenu will be gone.  right click the project and do either add->connected service and pick application insights, or right click add->application insights to see the same configure window as above, with the link at the bottom:
![local only in 2017](https://cloud.githubusercontent.com/assets/10158007/24874532/d9327774-1dd9-11e7-9d7c-73abaf78898c.png)

**Comment by Bartmax** [comment]
I see. Now understand what's going on, thank you for detailed explanation. Removing the nuget package enabled the local-only mode option.

My suggestion for improvement: include the link either it's installed or not (or at least tell the user something).

When I go to:

Create new Asp net core web application. Empty.
Go to connected services
It doesn't say that it's already  "connected"
So when you try to connect, you get this:

![image](https://cloud.githubusercontent.com/assets/3386797/24889287/7dda8d9c-1e3f-11e7-898c-9d689b5ec7ed.png)

![image](https://cloud.githubusercontent.com/assets/3386797/24889302/90c54bfe-1e3f-11e7-95f7-187540ba202d.png)

![image](https://cloud.githubusercontent.com/assets/3386797/24889351/df5c34f8-1e3f-11e7-86a2-b5f378da17dd.png)


From that UI what I see is, that even the SDK has been added, it looks like the process is incomplete until you connect to azure. very misleading imho.

Thanks for the clarification. Greatly appreciated.

**Comment by gardnerjr** [comment]
At one point in the past, that green bar at the top was a more standard looking green checkbox, and the red rectangle was an open circle, like this:

![old configwindow](https://cloud.githubusercontent.com/assets/10158007/24920299/8b584304-1e9b-11e7-9c76-056c28942ec5.png)

in this form, all of the "completed" steps were more obvious checkboxes, and all the "optional" things were open circles.  would this make it more obvious?

Yes, we don't consider your configuration it *complete* until you connect to azure, as without that, you aren't doing any real kind of telemetry, you're doing local diagnostics type work, since nothing ever gets stored.  But just because it isn't *complete* doesn't mean that it is *nonfunctional*.
