### ISSUE TITLE
visual studio 2017 built in web code analysis disabled for big files

### ISSUE THREAD

**Issue by guylando** [aspnet/Tooling#1046]
I can't find the configuration where i could specify the file size for this limitation. any ideas?
The right click on a big css\js file has the "run code analysis" button missing and the auto analysis is disabled too.
No documentation anywhere.
Barely any relevant google results for visual studio "web code analysis".
Where is this feature documentation??

**Comment by guylando** [comment]
Is this repository not-active? 11 days without an answer

**Comment by guylando** [comment]
Can you help? @madskristensen

**Comment by madskristensen** [comment]
The file limit is 35kb and there are no settings to change that. The reason is that the linters can go into stackoverflow when the file is too big

**Comment by mlorbetske** [comment]
@guylando yes, we're moving away from tracking issues on this repo in preference for [Visual Studio Developer Community](https://developercommunity.visualstudio.com/) as discussed in #1026. This move allows us to route issues across the different teams within Visual Studio and should encourage more direct contact with the engineers investigating issues.

Since @madskristensen has responded with the reasoning behind this not being a configurable setting, I'll close this - if you feel that this is something that merits further consideration, please open an issue on the Developer Community site.

**Comment by guylando** [comment]
Here is the issue just in case: https://developercommunity.visualstudio.com/content/problem/76212/visual-studio-2017-built-in-web-code-analysis-disa.html
