### ISSUE TITLE
Views in class libraries removed from embedded resources under certain circumstances

### ISSUE THREAD

**Issue by svallis** [aspnet/Tooling#1058]
I have a test repo which should hopefully demonstrate this problem, and I hope this is the correct repo for the issue.

https://github.com/svallis/precompilation-classlib

If you clone and open this solution and perform the following, the issue should be clear. First, the expected results is what happens when adding views to `app`:

- Go to `app1\Views\Home` and press SHIFT+F2 and create `Test.cshtml`
- Copy and paste the new file to end up with `Test - Copy.cshtml`
- Build the solution
- The `.csproj` file for `app1` remains unchanged

Now perform the same process on `lib1`:

- Go to `lib1\Views\Shared` and press SHIFT+F2 and create `Test.cshtml`
- Copy and paste the new file to end up with `Test - Copy.cshtml`
- Build the solution
- The `.csproj` file for `lib1` has the following added to it

```
<ItemGroup>
    <EmbeddedResource Remove="Views\Shared\Test - Copy.cshtml" />
</ItemGroup>
```

As you can imagine this is highly frustrating during development, and we're constantly running into it while developing features within a library. I don't know if it's an outright bug, or whether we could improve the existing rules in the `.csproj` for the library. Whatever changes are made to the library project file need to preserve existing functionality though, so that views are not included in the publish output and are embedded in the assembly. This allows everything to work both during development and after publishing with precompiled views.

**Comment by barrytang** [comment]
To report new issues, use the [Report a Problem](https://developercommunity.visualstudio.com/) tool. The GitHub Issue Tracker for the aspnet/Tooling repo is now deprecated in favor of the Report a Problem tool.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.
