### ISSUE TITLE
Support dotnet watch in launchSettings.json

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Tooling#1067]
I used to be able to use `dotnet watch` in Visual Studio by adding the following section to `launchSettings.json` and starting the project without debugging using CTRL + F5.

```
    "Kestrel (dotnet watch run)": {
      "commandName": "Executable",
      "executablePath": "C:\\Program Files\\dotnet\\dotnet.exe",
      "commandLineArgs": "watch run",
      "launchBrowser": true,
      "launchUrl": "https://localhost:5001/",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
```

This used to work in ASP.NET Core 1.1 but no longer does. According to https://github.com/aspnet/DotNetTools/issues/404 the new format for ASP.NET Core 2.0 is:

```
   "Kestrel (dotnet watch run)": {
      "commandName": "Executable",
      "executablePath": "C:\\Program Files\\dotnet\\dotnet.exe",
      "commandLineArgs": "watch run",
      "workingDirectory": "C:\\Users\\namc\\source\\repos\\WebApplication2\\WebApplication2",
      "launchBrowser": true,
      "launchUrl": "https://localhost:5001/",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
```

The problem with this is the hard coded `executablePath` which is Windows specific and the `workingDirectory` which is specific to wherever I did a Git clone on my local machine.

**Comment by barrytang** [comment]
To report new issues, use the [Report a Problem](https://developercommunity.visualstudio.com/) tool. The GitHub Issue Tracker for the aspnet/Tooling repo is now deprecated in favor of the Report a Problem tool.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.

**Comment by barrytang** [comment]
Adding @BillHiebert, @abpiskunov and @balachir as FYI.

**Comment by RehanSaeed** [comment]
Posted to the 'Report a Problem' tool with the same title as this issue.

**Comment by dharmaturtle** [comment]
@RehanSaeed to address your question in the [previous thread](https://github.com/aspnet/DotNetTools/issues/404#issuecomment-371752226):

>Is there a way to make the working directory more generic? Having to hard code a path in there is sub-optimal.

You can use `"workingDirectory": "$(ProjectDir)",`
