### ISSUE TITLE
auto build on browser request not working

### ISSUE THREAD

**Issue by sinand** [aspnet/Tooling#1079]
I am using community edition 15.9.3 since  the previous update this feature is not working, everytime I have to build project.

**Comment by barrytang** [comment]
Hi, can you see if you have the following setting turned on?

![image](https://user-images.githubusercontent.com/1648865/49671161-d0445400-fa1b-11e8-92ca-df6ec6133fbe.png)

Also, to report new issues, use the [Report a Problem](https://developercommunity.visualstudio.com/) tool. The GitHub Issue Tracker for the aspnet/Tooling repo is now deprecated in favor of the Report a Problem tool.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details. 

cc @BillHiebert
