### ISSUE TITLE
Support custom tools generators

### ISSUE THREAD

**Issue by a99cl208** [aspnet/Tooling#124]
Hi,

Have you planned the support custom tools generation for T4 ans resx files support for instance? Actually none of them can be added to a dnx project.

Thanks.

**Comment by sayedihashimi** [comment]
@a99cl208 we have a discussion on this at https://github.com/aspnet/Home/issues/272. I'll be replying on that thread soon. In short, its on the plan.

I'll close this item, let continue at the link above.

**Comment by michael-x** [comment]
@sayedihashimi the discussion over at aspnet/Home#272 seems to have been closed due to the fact that .tt support has been added, but a more general support for custom tools/single file generators still seems to be missing. Maybe you would consider reopening this ticket to track progress on that?
I also left comments on #339, but that ticket is more concerned with the access modifiers on the Resx generators, not choosing an entirely different custom generator.

**Comment by sayedihashimi** [comment]
@michael-x thanks for the feedback.

I have created a new item for the more general case https://github.com/aspnet/Tooling/issues/394. Let's discuss there.
