### ISSUE TITLE
adding comments in json files

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#13]
Using the comment selection keyboard shortcut inside the json file the **//** comment is added.
This is wrong and running for example the bower install task with comments in the bower.json I obtain the message **Fatal error: Failed to read ...\bower.json**

**Comment by glen-84** [comment]
Microsoft should push for comments to be included in the JSON spec. The reasons for it not being included are weak.

**Comment by madskristensen** [comment]
@lucamorelli Comments are being flagged as invalid if used in bower.json and package.json since Visual Studio 2015 RC. 

@glen-84 Comments are not illegal according to the JSON spec directly. The spec outlines what is valid JSON but states that parsers can expand the feature set as long as they also support the JSON spec.

**Comment by glen-84** [comment]
@madskristensen,

Comments were once part of the spec (see [here](https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr)). 

The moment a parser expands the feature set, the document can no longer be parsed by other parsers. It's not at all intuitive that you can comment in project.json but not in bower.json or package.json. This is why it should be part of the spec once again, and why I thought it would be interesting to see how the spec writers would respond to such a request from a large corporation.
