### ISSUE TITLE
DNX command for Console application seems to be too verbose

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Tooling#161]
I've added changes for `beta7` for generator-aspent:
https://github.com/OmniSharp/generator-aspnet/pull/321/files

and I've noticed that `dnx` command to run console application is now very verbose `ConsoleApplication`. It's even more verbose than command in home samples:
https://github.com/aspnet/Home/blob/dev/samples/latest/ConsoleApp/project.json#L6

The other commands are short, easier to memorize:
http://docs.asp.net/en/latest/dnx/overview.html?highlight=commands#dnx-concept-commands
https://github.com/aspnet/Home/blob/dev/samples/latest/HelloMvc/project.json#L21-L22

Such verbose commands introduce even more problems, see docs for console application that uses both `run` and custom command name:
http://docs.asp.net/en/latest/dnx/console.html?#running-the-app

I think it would be easier for end users and to document proper new software features to use short version, that was used in `beta6` (and older) templates:
```
dnx . run
```
(or):
```
dnx run
```

**Comment by sayedihashimi** [comment]
Thanks @peterblazejewicz, that change was made in the Visual Studio templates a release or so ago. I think @rustd and @DamianEdwards would be interested in this discussion.

I agree that `dnx run` is better than `dnx ConsoleApplication`. I'm not sure the reason why we switched but a possible reason would be to be consistent with standard C# console app projects. In that case the .exe created matches the project name. The difference when using the terminal is that you can use autocomplete for the .exe name but not for dnx command names. IMO even though it's not consistent with standard projects it's justified because it improves usability.

@rustd @DamianEdwards have you heard any other feedback on this?

**Comment by peterblazejewicz** [comment]
It appears to be by design, see Damian Edwards comments about commands section for Console Application:
https://youtu.be/G5yHPlpTfHU?t=57m37s
It should be documented though.

**Comment by davidfowl** [comment]
The generated executables are based on the command names. That's why it matches the application name

**Comment by peterblazejewicz** [comment]
Thanks for update!
