### ISSUE TITLE
New classes created with refactoring are created in root of ASPNET5 project instead of folder.

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/Tooling#189]
When I create a new class via the "Create class' refactoring in VS2015, it creates it in the root of the project. I am happy to create short video to show. I have only webessentials installed as an extension (no other extensions).

**Comment by sayedihashimi** [comment]
I've never seen this before could you do the video?

**Comment by shawnwildermuth** [comment]
Here you go (there isn't audio, but I repro the issue). Note I forgot that I do have Mads' New File extension in case that's also involved, but I can't imagine:

https://youtu.be/BRgJeEmeUzo

**Comment by sayedihashimi** [comment]
@shawnwildermuthThat dialog is created by the extension by Mads I think its a bug in that extension.

**Comment by shawnwildermuth** [comment]
It's not the dialog (that file works fine), it's when I use Ctrl-. to build a new class via refactoring...I can re-do it with Mads extension disabled...But to be clear...it's Refactoring that is creating the file. Not the dialog you see early in the video.

**Comment by sayedihashimi** [comment]
@shawnwildermuth sorry about that. Now I see what you mean.

@BillHiebert @barrytang In the video you can see the issue starting at [1:15](https://youtu.be/BRgJeEmeUzo?t=1m15s)

I have a screenshot as well.
![refactor-class](https://cloud.githubusercontent.com/assets/1283154/9918227/78df6962-5c7a-11e5-9f3f-643e4b41a533.png)

When this menu option is used instead of placing the file in the `Models` folder it goes to the project root.

**Comment by shawnwildermuth** [comment]
Here is another more annotated version without the extensions installed just in case:

https://youtu.be/94PlnvsZMq0

**Comment by sayedihashimi** [comment]
TFS:149240

@shawnwildermuth we've added it to our TFS bug tracker, will reply back here soon.

**Comment by shawnwildermuth** [comment]
Thanks, is this making it into beta8

**Comment by sayedihashimi** [comment]
This is being tracked at https://github.com/dotnet/roslyn/issues/8342 I'll close this now.
