### ISSUE TITLE
Automatic File Nesting broken in Beta 7

### ISSUE THREAD

**Issue by TylerWoods** [aspnet/Tooling#196]
When my team went from Beta 6 to Beta 7, we installed the web tooling for Visual Studio 2015 (WebToolsExtensionsVS14.msi).  However, this update seems to have broken the automatic file nesting as shown here

![nesting](https://cloud.githubusercontent.com/assets/14822762/10075850/b62c3498-629d-11e5-91d6-dd0d020c596d.jpg)

Prior to this, the config.XXX.json files all were nested under config.json.  Now, only the first (alphabetically) is nested.   This seems like the worst of both worlds - some (seemingly random) files are hidden, but not enough to make the solution manageable.

We are using the file nesting for not just resources (like xxx.min.js or config.json) but also for other file types and have found it to be quite useful until this latest change.

**Comment by BillHiebert** [comment]
@abpiskunov

**Comment by abpiskunov** [comment]
TFS bug: 148634

**Comment by abpiskunov** [comment]
Its fixed in beta8

**Comment by JonTheMon** [comment]
Are all file types supported for nesting? I ask because I'm getting this behavior:

![file-nesting](https://cloud.githubusercontent.com/assets/12816887/11148212/fd987084-89e0-11e5-83c2-752afdb702e7.png)

These files are in a folder under Views. I have a view with many sub-parts, so I've broken it out into separate sub-views and named them accordingly, but they don't nest properly. 

I do have the Beta8 WebToolsExtensions for Visual Studio 2015
