### ISSUE TITLE
Live reload browser on save

### ISSUE THREAD

**Issue by r03** [aspnet/Tooling#213]
I would be nice if the linked browser would automatically refresh on save.
There is the browser link option, but on save would be nicer.
It should also be faster then the refresh with browser link.
If have no problem with installing a live reload plugin in the browser if that is needed.

The question was first asked here:
http://stackoverflow.com/questions/33034169/live-reload-with-asp-net-5

**Comment by RehanSaeed** [comment]
+1

**Comment by BillHiebert** [comment]
@jodavis

**Comment by sayedihashimi** [comment]
Assigning to @madskristensen because this seems related to browser link. Mads, if you think I should follow up let me know.

**Comment by madskristensen** [comment]
This is tracked in TFS

**Comment by r03** [comment]
Does this mean it will get implemented in the near future or is it on the 'maybe someday' list?

I guess I could use something like this for now: 
https://github.com/vohof/gulp-livereload

**Comment by Mangor** [comment]
+1

**Comment by BenevidesLecontes** [comment]
+1

**Comment by marviobezerra** [comment]
+1

**Comment by madskristensen** [comment]
This is actually pretty easy to implement, but the reason we haven't is for any unforeseen consequences this would cause. However, let's build it in an extension really quick so you can all get the functionality as soon as possible. I assume it shouldn't be all file types that should should trigger the reload when saved? What about these:

- .html
- .cshtml/.vbhtml
- aspx
- .ascx
- .master
- .js

CSS reload on change is already built in, so no reason to add that one. There is a bug in ASP.NET Core projets where it doesn't work but that will be fixed

**Comment by madskristensen** [comment]
I built an extension that refreshes the browsers automatically on save. You can modify what file types should trigger the reload as well as folders to ignore (e.g. _/vendor/_ and _/node_modules/_).

Get it here https://visualstudiogallery.msdn.microsoft.com/46eef4d9-045b-4596-bd7f-eee980bb5450

As always, [this extension is open source](https://github.com/madskristensen/BrowserReloadOnSave) on GitHub, so please feel free to open bugs and suggestions on the [issue tracker](https://github.com/madskristensen/BrowserReloadOnSave/issues).

Also, feel free to blog and tweet about it.

**Comment by bastienJS** [comment]
@ms Thanks for listening to the end user :-) I tried your extension it works for javascript applications.

There is one gotcha for my case: I use typescript. On Save my .ts files are compiled to .js files in the wwwroot. Now your Refresh happens earlier than my ts compilation is finished thus the old javascript files are refreshed.

Running 2 monitors with VS + Browser and a instant refresh of my application code is a real time saver. I do not want to press ALT + STRG + ENTER after the TS compilation.

With WebStorm IDE That workflow works like a breeze...

Any idea how this can be implemented so that Microsoft script language number One can be used with VS productively?

**Comment by bastienJS** [comment]
@r03 That will work only for index.html file as static resource in asp.netcore. If  you have a index.cshtml file then gulp-livereload does not care...

**Comment by madskristensen** [comment]
@bastienJS I've built in an option to add a delay (the default is 250 milliseconds). This should fix the issue. Can you please help verify it in the latest CI build version 1.0.7 from here http://vsixgallery.com/extension/2d8aa02a-8810-421f-97b9-86efc573fea3/

**Comment by bastienJS** [comment]
I already deinstalled the extension. But well when Microsoft calls me ;-)

So I installed again and started from the default value 250 ms to 500 ms and to 750 ms then the current changes were shown in my self executing javascript function with an alert box.

It works yes - having 4 .ts files to compile - but what happens when my ts compilation will take longer someday - having 40 .ts files to compile - it will break for a user who touched the .ts files the first time. Poor guy ;-)

Seriously, I prefer the gulp way because it will always work:

```
gulp.task('watch', function () {
    gulp.watch("./wwwroot/app/", ['compile-ts']);
     
    browserSync.init({
      proxy: 'localhost:55555', // IIS express port
        notify: true,
        open: true,
        logLevel: 'debug',
        
    });

    gulp.watch(['./wwwroot/app/**/*.js','./wwwroot/app/site.css']).on('change', function (event) {
        console.log('File ' + event.path + ' was ' + event.type + ', doing page reload!');
        browserSync.reload();
    });

});
```

**Comment by madskristensen** [comment]
@bastienJS  the latest version (1.0.10) should now support this. I changed the implementation to use a Timer instead of just a FileSystemWatcher.

**Comment by bastienJS** [comment]
@madskristensen  Just saw your 1.0.11. Browsed a bit your changes, but you still use a

```
 _watcher = new FileSystemWatcher(folder);
```
in the ReloadExtension.cs

I am confused what you talk about! 

1.0.10 should support "this" what is this in my scenario? :-) Tell me and I try the extension again :-)

**Comment by madskristensen** [comment]
@bastienJS It still uses a `FileSystemWatcher` but that doesn't trigger the browser reload. A `Timer` triggers it

**Comment by bastienJS** [comment]
Thanks for the answer. So do I still have to set the delay to 3 seconds when I compile 100 .ts files to .js files?

Funny, but extension does not work here. The browser never refreshes.
1. I have all Reload stuff on enabled.
2. I change a .js files manually
3. I press strg + S
4. The .js file is in the wwwroot folder

Any idea?
