### ISSUE TITLE
Beta8 Installation fails

### ISSUE THREAD

**Issue by bbeda** [aspnet/Tooling#230]
I am trying to install Beta8 on VisualStudio 2015 Enterprise with Update 1 CTP and it fails by saying that it can't find the installer. I also tryied to uninstall/reinstall/repair Beta7 but it does the same. I also noticed that when I try to uninstall Beta7, the title from the uninstall windows says 'Beta8' so something has been corrupted along the way.
![vserror2](https://cloud.githubusercontent.com/assets/2919481/10601036/99e6ca00-7706-11e5-8100-2e98d8173cad.PNG)
![vs error 1](https://cloud.githubusercontent.com/assets/2919481/10601035/99e4adec-7706-11e5-9b53-584cf46ee2b5.PNG)

**Comment by BillHiebert** [comment]
@joeloff

**Comment by joeloff** [comment]
- Copy the Beta8 download to another folder
- Download the Beta7 MSI, then drop it C:\Users\bbeda\Downloads
- Try to uninstall Beta 7
- Install/Repair Beta8

The installers have the same name, but the installer service in the OS will try to cache packages and when it tries to remove the old product during the upgrade, can prompt you for the original location from where you installed it. Since that location likely has the Beta8 copy, it will realize the packages are not the same and prompt you for the original source.

**Comment by bbeda** [comment]
I already had them both in downloads and I was manually selecting the beta7 file. I removed the beta8 and put the original name on beta7 and it worked fine.

Thank you
