### ISSUE TITLE
Global.json missing from Beta8 Templates

### ISSUE THREAD

**Issue by jderus** [aspnet/Tooling#267]
I just upgraded to the Beta8 tooling and created a new project using the ASP.Net 5 preview template. This seems to no longer create a global.json file. Is that an intended change? 

global.json used to be created as part of the template. I see it is still talked about in the documentation here: http://docs.asp.net/en/latest/tutorials/your-first-aspnet-application.html. And I saw it on the structure markdown here: https://gist.github.com/davidfowl/ed7564297c61fe9ab814 .

Is this the correct place for the issue, or can you point me in the right direction?
Thanks.

**Comment by sayedihashimi** [comment]
Hi @jderus, thanks for opening the issue.

When you create a project to get the `global.json` file + folder structure please make sure that the `Create directory for solution` is checked. If you uncheck that then the solution/project is created w/o the extra files + folders.

![newproject](https://cloud.githubusercontent.com/assets/1283154/11043587/4c05e18c-86d2-11e5-9809-8a97280ea1eb.png)

I'm pretty sure that is what you're running into so I'll go ahead and close this now. If you are facing something else please reopen this so that we can investigate it.

**Comment by jderus** [comment]
Yep, you are right.
I did not remember having that checked before, but I got someone to verify that this was indeed the behavior before Beta8.

Looks like a bad memory PEDKAC on my part. Sorry!

**Comment by sayedihashimi** [comment]
Ok thanks for confirming.
