### ISSUE TITLE
NuGet Package Manager Console hangs when running npm init

### ISSUE THREAD

**Issue by cveld** [aspnet/Tooling#329]
I am using Visual Studio 2015 - starting with ASP.NET 5 RC it looks like package.json is hidden by default from the solution explorer. It took me a while to find the Dependencies -> NPM -> Context menu entry point to open up package.json. 
Before I found out I tried to create package.json by running `npm init` from the NuGet Package Manager Console. This resulted in console interaction which looks like not to be supported by this particular Console window, resulting in a hang of the window. After having closed it, I can't reopen it. The open is greyed out in the Tools -> NuGet Package Manager menu. It looks like I now need to restart Visual Studio to get the Package Manager Console working again.

I also tried out the PowerShell interactive window, to no avail: it keeps popping up Read-Host dialog screens, I see some progress, but it never finishes.

What to do? What is the best way to run command-line tooling from within Visual Studio that requires console interaction?

**Comment by bab5139** [comment]
Is node's package manager connected with the nuget packagement console?  Typically you don't need to interact with the npm command since npm install is run on project open, any time you edit the package.json file and can also be run by right clicking the dependencies folder and running install packages.  I wouldn't have though to run npm related stuff through the nuget package manager console but may be its possible.

**Comment by BillHiebert** [comment]
@yishaigalatzer

**Comment by yishaigalatzer** [comment]
The package manager console is very limited and intended to interact with the visual studio process. I wouldn't call it a general command line you can run from within visual studio. I use a powershell window external to visual studio.

**Comment by sayedihashimi** [comment]
>ASP.NET 5 RC it looks like package.json is hidden by default from the solution explorer. It took me a while to find the Dependencies -> NPM -> Context menu entry point to open up package.json. 

Good feedback for @madskristensen

**Comment by sayedihashimi** [comment]
This issue is pretty old. We recently released RC2 https://blogs.msdn.microsoft.com/webdev/2016/05/16/announcing-asp-net-core-rc2/. I'm hoping that this is no longer an issue so I'm closing this. If this is still an issue with RC2 please reopen this.

**Comment by alantrick** [comment]
I don't think I have the ability to reopen this, but I just ran into this problem.

**Comment by TVerheggen** [comment]
I also just had this problem on VS 2017.  But will use powershell as recommended.

**Comment by travisterrell** [comment]
I want to confirm that this issue still exists in January of 2018.

**Comment by barrytang** [comment]
To report new issues, use the [Report a Problem](https://developercommunity.visualstudio.com/) tool. The GitHub Issue Tracker for the aspnet/Tooling repo is now deprecated in favor of the Report a Problem tool.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.

**Comment by juniebugs** [comment]
This problem still exists.

**Comment by barrytang** [comment]
To report new issues, use the [Report a Problem](https://developercommunity.visualstudio.com/) tool. The GitHub Issue Tracker for the aspnet/Tooling repo is now deprecated in favor of the Report a Problem tool.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.

**Comment by mukeem1** [comment]
Still facing same issue in vs 15.9.4
