### ISSUE TITLE
Task Runner Explorer does not recognize linked Grunt file

### ISSUE THREAD

**Issue by beyti** [aspnet/Tooling#366]
Adding the grunt file within a folder to a project like below
    `<ItemGroup>`
        `<Compile Include="relativepathoffolder\**\*.*">`
            `<Link>%(RecursiveDir)%(FileName)</Link>`
        `</Compile>`
    `</ItemGroup>`
results in "Task Runner Explorer" to not recognize this as a task file.
Instead of doing like above, if added as a content but not link; same file is recognized by the TRE.

**Comment by madskristensen** [comment]
TRX doesn't change the behavior of Grunt based on what is inside the .csproj file. TRX will work if the scenario work on the command line without VS. Does your scenario work from the command line?

**Comment by beyti** [comment]
I think I've been misunderstood but it's ok.
In VS, when we link items but not show them as a content, it's useful for avoiding replicas.

I thought, it would be lovely if we could use TRX in that scenario too but as far as I can understand, TRX wants the necessary files to be in the directory of project strongly. Right?

**Comment by madskristensen** [comment]
The Grunt support in TRX is very purposefully and deliberately limited to what is possible on the command line. There is no way a linked gruntfile.js would work outside of VS since it augments the way Grunt (and node.js dependency resolution) works. It would completely break down on the command line.

In light of that I have to close this issue. Unless Grunt adds support for a way to have lined files or shadow files, then we're not adding support for it to TRX.
