### ISSUE TITLE
New Project dialog framework selection drop-down too narrow

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Tooling#391]
When selecting a .NET Framework version such as 4.5.1, 4.5.2, or 4.6.1 from the New Project dialog, I find myself second-guessing whether it was actually selected in the drop-down. This drop-down should be a bit wider, so that I can easily determine whether the desired framework version was selected. See the animated gif below.

![new project dialog](https://cloud.githubusercontent.com/assets/10702007/12805688/8014abcc-cac3-11e5-8d52-637418865abf.gif)

**Comment by sayedihashimi** [comment]
Thanks @scottaddie. I see that you have [SideWaffle](http://sidewaffle.com/) installed which is great!

This repo is more for items that are specific to ASP.NET 5. I'll keep this open and I'll try and track down who owns this from the VS side so that they can see this feedback. I'll likely close it in a week or so since there is no action on my team here.
