### ISSUE TITLE
Scaffold a EF view error. Using Preview1

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#478]
Version Information: 
``` 
dotnet --version
1.0.0-preview1-002702

SDK: dotnet-dev-win-x64.1.0.0-preview1-002702

VS2015 Tools Preview 1
```

Repro:

Create new web project.
Add dependency:  `"WindowsAzure.Storage": "7.0.1-preview"`
Make a class `AzureService.cs` (or any name) with at least one method using `CloudBlobContainer`

Try to scaffold a Edit view:

![image](https://cloud.githubusercontent.com/assets/3386797/15270886/19a8c796-1a06-11e6-9f2b-3c3e18c13382.png)

removing the class gives no error.

**NOTE:** While this dependency is not yet ready for RC2, I think it would be great to notify this behavor as soon as possible because the file that generates the conflict has nothing to do with the dbcontext or scaffolding. It's an arbitrary file using an arbitrary dependency package.

Interesting, EF migrations/update works flawlessly.

**Comment by GuardRex** [comment]
Not really sure this is a bug. The main project `imports` including `portable-net45+win8` is masking all of this. That particular dep is just downright :skull: dangerous :skull: pinned to DNX-era packages (rc1-final). I still suggest deps that are passing on restore due to an `imports` specification should get a warning on restore.

**Comment by sayedihashimi** [comment]
TFS: 224875
I've added this to our internal TFS, we will reply back here soon.

**Comment by prafullbhosale** [comment]
@Bartmax I could not repro based on the steps above. 

The model I am using to repro below is like below: 

```
    public class Cloud
    {
        public int ID { get; set; }
        public string Name { get; set; }

        private CloudBlobContainer _container;

        public CloudBlobContainer GetCloudBlobContainer()
        {
            return _container;
        }

        public Cloud()
        {
            _container = new CloudBlobContainer(new Uri(""));
        }
    }
```

Am I missing something?

**Comment by Bartmax** [comment]
You are right. There one more piece of code that's needed for it to break. Try adding this to your cloud class:

```
public async Task ThisMakesItBreak()
        {
            var container = GetCloudBlobContainer();
            await container.SetPermissionsAsync(new BlobContainerPermissions
            {
                PublicAccess = BlobContainerPublicAccessType.Blob
            });
        }
```

and try scaffold a view again. You should see the error now.

**Comment by prafullbhosale** [comment]
Thanks @Bartmax! 
I was able to repro the issue. 
The problem seems to be that when Scaffolding tries to compile the project using Roslyn workspace, it doesn't resolve the reference versions properly. 

As a workaround if I upgrade to `"WindowsAzure.Storage": "7.0.2-preview"` I don't have the issue anymore.

**Comment by prafullbhosale** [comment]
Created an issue in the dotnet cli repo for this: 
https://github.com/dotnet/cli/issues/3634

**Comment by sayedihashimi** [comment]
Closing in favor of https://github.com/dotnet/cli/issues/3634
