### ISSUE TITLE
Cannot Hide a Folder on Visual Studio 2015 Update 2 and ASP.net Core RC2

### ISSUE THREAD

**Issue by frapid** [aspnet/Tooling#491]
```
<DnxInvisibleFolder Include="Areas" />
```

The `DnxInvisibleFolder` does not hide a folder from Visual Studio:

Visual Studio freezes if I try to "Hide from Solution Explorer".

**Comment by sayedihashimi** [comment]
TFS: 223015
I've added this to our internal TFS, we will reply back here soon.

**Comment by frapid** [comment]
Update:

1. The freezing happens only when the option "Show Hidden Files" is on.
2. Visual Studio does not display the hidden (greyed out) icon for the `DnxInvisibleFolder` directory.

**Comment by abpiskunov** [comment]
@frapid  could you share your solution please? We need to see if your folder is too big or it's something else.

**Comment by abpiskunov** [comment]
and what exactly are your repro steps? Could you please specify step by step repro?

**Comment by abpiskunov** [comment]
The reason i ask for details is i can not repro the freeze you mentioned.
I can see that folder's icon is not changed to gray icon when it is hidden and Show All Files button is checked, but this is a known limitation and we can not changed that. It happens because when we hide the folder we don't really exclude it from project, only folders/files excluded from project are grayed out.

SO the only thing to investigate is freeze and i need your solution with repro steps...

**Comment by abpiskunov** [comment]
@frapid Did not hear back for a week and can not repro the freeze mentioned in the issue - closing it for now. If freeze repro again, please attach a sample solution (zip) and reactivate this issue.
