### ISSUE TITLE
NRE on Publish settings and crash

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#502]
Opening the publish settings if I go to settings I get NRE and then VS crashes.
Closing it make it VS crashes.

I get this everytime with the project/solution I'm currently working on.(not sure what is causing it, worked before)

![pasted image at 2016_05_19 05_55 am](https://cloud.githubusercontent.com/assets/3386797/15388084/9a4653b8-1d86-11e6-8c05-4582ffed7ba2.png)
![pasted image at 2016_05_19 05_55 am 1](https://cloud.githubusercontent.com/assets/3386797/15388083/9a44b968-1d86-11e6-91e2-654875532f47.png)

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg You encountered this in verification didn't you? Was there an associated issue with what you found or am I misremembering?

**Comment by ryanbrandenburg** [comment]
I did not encounter this, the problem I saw happened only on the Create Azure App Service screen, and it didn't throw an error, it just hung VS.

**Comment by vijayrkn** [comment]
This happens while trying to retrieve the default connection string information for the web app and the Azure login information is not available (either credentials expired/logged out of Azure). This issue is already fixed in the next Azure SDK release. Logging into Azure from the server explorer should fix this.

If you are getting this error while publishing to a slot, then logging in won't help. In this case the temporary work around would be to re-name your appsettings.json before publishing. A fix for this is also available in the next Azure SDK release.

**Comment by Bartmax** [comment]
@vijayrkn thank you.
