### ISSUE TITLE
entity framework tools for vs are not included

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#53]
Hi,
  from what I see inside visual studio 2013 the commandlets Enable-Migrations and Add-Migration are installed with entity framework tools for vs.
  a similar tool is not installed with vs 2015 rc, so is not possibile to use migrations with asp.net 4 application in vs 2015. If in the same computer is already installed vs 2013 the command are available, so looks like that vs 2015 use the same files installed but ef tools for vs 2013, but I cannot install ef tools for 2013 in a system where noly vs 2015 is installed, because the setup doesn't find vs 2013, so I cannot use migrations.

**Comment by muratg** [comment]
@bricelam has some information on http://www.bricelam.net/2014/12/16/ef7-migrations-designtime.html

**Comment by bricelam** [comment]
The NuGet commands are installed with the EntityFramework (for EF6) or EntityFramework.Commands (for EF7) package. Not with the EF Tools for VS.

In order to install the EF Tools for VS, ensure that either the SQL Server Data Tools or the Web Developer Tools are selected:

![image](https://cloud.githubusercontent.com/assets/1226749/7460472/22bbc94a-f258-11e4-9b24-5c03151571c4.png)

**Comment by sayedihashimi** [comment]
I'll go ahead and close this, but if you are still having issues please open an issue at https://github.com/aspnet/EntityFramework.
