### ISSUE TITLE
KB3151378

### ISSUE THREAD

**Issue by wangkanai** [aspnet/Tooling#582]
patch wouldn't download or find the packages.
![image](https://cloud.githubusercontent.com/assets/10666633/16013306/282dcd2a-31b7-11e6-9ee0-6ffdab5fd5f7.png)

**Comment by sayedihashimi** [comment]
TFS: 231109

**Comment by sayedihashimi** [comment]
@wangkanai thanks for the report. This doesn't look to be related to ASP.NET or .NET Core. This repo is for tracking ASP.NET/.NET Core specific items. I don't think we have a good repo for general Visual Studio feedback. I think the best that we currently have is [Microsoft Connect](https://connect.microsoft.com/). I think your best option is to create a new connect bug, hopefully you'll be routed to the right team. I'm going to close this since it's external.
