### ISSUE TITLE
klr.exe continuously crashing with a circular reference

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#6]
I created an asp.net 5 console app and a library class, and I tried to create a circular reference adding to both projects a reference to the other.
As I completed the circular reference this message started to appear

![untitled](https://cloud.githubusercontent.com/assets/127777/6525663/53af5e00-c408-11e4-8d76-0894f82420a0.png)

If I close this dialog reappear in a few seconds and I haven't found a way to stop it.

**Comment by BillHiebert** [comment]
The circular reference issue has been fixed in newer builds of the runtime. It now detects the circular reference and you get a nice message in the error list.  The endless restart of the KLR is a VS tooling issue. VS uses the KLR to get information about the project and when it crashes (or goes away for some other reason), it will restart it. In this case , restarting causes it to crash again and you get in this infinite cycle. There is a bug tracking getting this fixed.
