### ISSUE TITLE
Duplicate references in project.json break IntelliSense

### ISSUE THREAD

**Issue by ljani** [aspnet/Tooling#652]
I had a class library, which accidentally had duplicate entries as dependencies:

```
{
  "dependencies": {
    "Microsoft.EntityFrameworkCore.Design": {
      "type": "build",
      "version": "1.0.0-preview2-final"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        },
        "Microsoft.EntityFrameworkCore.Design": {
            "type": "build",
            "version": "1.0.0-preview2-final"
        }
      }
    }
  }
}
```

Notice that the dependency `Microsoft.EntityFrameworkCore.Design` is mentioned twice.

Referencing this from an another project makes VS2015u3 with tooling preview2 not to be able to resolve any references to types in the class library (`The type or namespace MyClass could not be found`).

The build completes fine from VS and cli, but IntelliSense claims there are errors. In fact, when I check the errors tab, I see errors even if  the build completed just fine (on the Output tab)!

**Comment by ljani** [comment]
Here's how to reproduce this:
https://github.com/ljani/aspnet-tooling-issue652

**Comment by mlorbetske** [comment]
TFS Bug#237384

**Comment by mlorbetske** [comment]
Sorry for the delay in responding. While this is less than ideal, it does have an easy workaround - removing the duplicated references. Since the focus for .NET Core tools has shifted to Visual Studio 2017 (where the experience around adding/managing references is much better), we do not plan to invest in additional project.json based experiences.
