### ISSUE TITLE
issues with nuget

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#68]
A couple of things:
1. looks like nuget configuration is shared between vs 2013 and vs 2015. If I have both installed changing the configuration in vs 2015 is applied to vs2013 too.
2. It's not clear which are the differences between nuget api v2 and v3. If v3 is just for asp.net 5 it's better to split based on the active project, and give a warning if you are using the wrong feed. Often I receive errors with v3 and I have to switch back to 2, and I found in stackoverflow several questions about people that install npsql and mongodb driver (that seems to be ef 6 drivers) in asp.net 5 project and are not able to compile.

**Comment by mayurid** [comment]
@yishaigalatzer :could Nuget take a look?

**Comment by yishaigalatzer** [comment]
The configurations are shared by design. V3 is the new nuget.org server architecture, that applies to all projects (not just ASP.net 5). You will see much faster search with it and much faster restores. On out side it makes the server a lot more efficient letting as scale out easily.

There is a bug in the rc release where the v3 sources are not suppressed by the older v2 client. We plan to release a 2.8.6 extension for down level that solves that and deduplicates sources.

Can't help with the stack overflow questions. You might want to open a separate issue against thebef repo

**Comment by yishaigalatzer** [comment]
Done

-----Original Message-----

**Comment by sayedihashimi** [comment]
Closing this now as there doesn't seem to be any more action in this repo.
