### ISSUE TITLE
Microsoft .NET Core 1.0.0 VS 2015 Tooling Preview 2 installer fails

### ISSUE THREAD

**Issue by LeeChenelerJS** [aspnet/Tooling#708]
I have VS Studio 2015 installed with all the updates and yet the installer still fails. Extract frm log of failed conditions. 

> [27D0:1064][2016-08-03T18:00:00]i052: Condition 'WixBundleInstalled OR NOT(((VS2015CommunityUpdateVersion <> VS2015UpdateVersion) AND (VS2015CommunityExists) AND (VS2015UpdateVersionExists)) OR ((VS2015ProfessionalUpdateVersion <> VS2015UpdateVersion) AND (VS2015ProfessionalExists) AND (VS2015UpdateVersionExists)) OR ((VS2015EnterpriseUpdateVersion <> VS2015UpdateVersion) AND (VS2015EnterpriseExists) AND (VS2015UpdateVersionExists)) OR ((VS2015WebExpressUpdateVersion <> VS2015UpdateVersion) AND (VS2015WebExpressExists) AND (VS2015UpdateVersionExists))) OR (SKIP_VSU_CHECK=1) OR (WixBundleAction=2)' evaluates to false.
> [27D0:1064][2016-08-03T18:00:00]e000: Setup has detected that Visual Studio 2015 Update 3 may not be completely installed. Please repair Visual Studio 2015 Update 3, then install this product again.
> [27D0:1064][2016-08-03T18:00:00]e000: Error 0x81f40001: Bundle condition evaluated to false: WixBundleInstalled OR NOT(((VS2015CommunityUpdateVersion <> VS2015UpdateVersion) AND (VS2015CommunityExists) AND (VS2015UpdateVersionExists)) OR ((VS2015ProfessionalUpdateVersion <> VS2015UpdateVersion) AND (VS2015ProfessionalExists) AND (VS2015UpdateVersionExists)) OR ((VS2015EnterpriseUpdateVersion <> VS2015UpdateVersion) AND (VS2015EnterpriseExists) AND (VS2015UpdateVersionExists)) OR ((VS2015WebExpressUpdateVersion <> VS2015UpdateVersion) AND (VS2015WebExpressExists) AND (VS2015UpdateVersionExists))) OR (SKIP_VSU_CHECK=1) OR (WixBundleAction=2)
> [27D0:1064][2016-08-03T18:00:00]i199: Detect complete, result: 0x0

Any advice/ thoughts?

**Comment by babarqb** [comment]
Open command prompt where you save preview2 exe file and  use this command 
 [preview2 full name.exe] SKIP_VSU_CHECK=1

It installed without any error but vs2015 update 3.4 could not load preview tooling   im still waiting update of vs preview2 tooling

**Comment by LeeChenelerJS** [comment]
Thanks for the reply, yes I tried this last night. However ti still fails, upon closer inspection is seems to be failing to install NuGet, I'll finish my investigation and post back

**Comment by LeeChenelerJS** [comment]
So it would appear it was a NuGet installation issue. I'm not entirely sure as to the route cause, however I think it probably has something to do with the way my corporate laptop is set up -.- we have a bunch of crap thats constantly running on it which includes a load of rubbish McAfee security things that randomly decides to hold onto files etc in its process. Anyway, I couldn't uninstall my current NuGet through VS because a process was holding onto it all, so I manually removed its folder in VS 2015's Extensions folder and reran the installer, now it installs fine.

**Comment by babarqb** [comment]
Great news atleast you got success. But i face still same issue Vs2015 update3.4 as same version like yours. infect i raised issue here on github but still no answer. could you please write down here vs 2015 info.  Mean go to help menu and check copy info there and paste here.

**Comment by LeeChenelerJS** [comment]
@babarqb  Microsoft Visual Studio Professional 2015
Version 14.0.25425.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Professional

LightSwitch for Visual Studio 2015   00322-40000-00000-AA609
Microsoft LightSwitch for Visual Studio 2015

Visual Basic 2015   00322-40000-00000-AA609
Microsoft Visual Basic 2015

Visual C# 2015   00322-40000-00000-AA609
Microsoft Visual C# 2015

Visual C++ 2015   00322-40000-00000-AA609
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.20624.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.8.1   14.0.11123.0
Azure App Service Tools v2.8.1

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft .NET Core Tools (Preview 2)   14.1.20624.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

StyleCop   4.7
Provides source code style and consistency tools. See https://github.com/Visual-Stylecop/Visual-StyleCop for more details.

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

**Comment by babarqb** [comment]
So nice of you and bundle of thanks for giving me time and pasting here your info. I have missing these two things 
Microsoft .NET Core Tools (Preview 2) 14.1.20624.0
Microsoft .NET Core Tools (Preview 2)

i dont know where is problem why vs 2015 not load this i face this problem last two days. Any way thanks once again.

**Comment by joeloff** [comment]
@LeeChenelerJS It looks like you have VS Professional installed? Can you please check the following entries in the registry and tell me which keys you have under HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\DevDiv\vs\Servicing\14.0

Are there any entries for enterprise? We've seen a few instances where users have keys for SKUs they don't have. We had one customer that had a key for professional when they only had community installed. NuGet needs to detect the exact SKU since it needs to pass that information to the VSIX installer. If it finds a SKU different from the one that's actually installed, the VSIX installer will fail.

**Comment by LeeChenelerJS** [comment]
@joeloff No there isn't the reg looks like its all for the professional SKU like it should be :) 

I think my issues were probably all caused by my corporate laptop.... don't have any issues on my personal machine.

**Issue 1: Not thinking VS 2015 Update was properly installed**
I think that something in the update 3 installer was blocked from properly installing because my laptop s security software randomly chooses to lock files in its process... so the "*SKIP_VSU_CHECK=1*" solution solved that.

**Issue 2: Failed to install Microsoft NuGet during Core Tooling installer**
The issue here was basically the same. I couldn't manually uninstall Nuget Package manager from within VS because a process was holding onto it. To combat this I had to manually delete its folder from "*C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions*" then rerun the installer.

Hope this helps anyone else who is having similar trouble.

**Comment by cremor** [comment]
@joeloff I've just updated from Update 2 to Update 3 today and now have the same problem installing the .NET Core tools. I've already installed them with the SKIP_VSU_CHECK=1 switch, but to help you diagnose the problem here are the registry keys you mentioned with their value in "UpdateVersion".

Note: I've only ever had Visual Studio Enterprise installed on this machine. Help-About shows "Version 14.0.25425.01 Update 3"

bslnneu: 14.0.25425
community: 14.0.25425
devenv: **14.0.25420**
enterprise: 14.0.25425
lightswitch: **14.0.23928**
lightswitchv5tools: **14.0.23928**
lsv5sdk: **14.0.23928**
minshellcore: 14.0.25425
minshellinterop: **14.0.25420**
premium: 14.0.25425
professional: **14.0.25420**
RoslynLanguageServices: 14.0.25425
teamExplorerCore: **14.102.25521**
testToolsCore: **14.0.25420**

Maybe there is a problem with one of the [small updates](https://msdn.microsoft.com/en-us/library/mt752379.aspx) that were released some time after update 3? The update 3 setup seems to have installed that one for me automatically, since I'm already at the version mentioned on the linked page.

**Comment by joeloff** [comment]
Thanks @cremor 

We're working on a solution to relax the checks we perform. Up to Update 3, the version information was always guaranteed to be in sync. However, with the introduction of the small updates (KB3165756), the patches have become more targeted and that is what is tripping up the .NET Core installer right now.

**Comment by balachir** [comment]
@cremor, your issue should now be fixed as part of a [cumulative update](https://github.com/aspnet/Tooling/blob/master/release-notes.md#8112016-tooling-update-for-net-core-100---vs-2015-tooling-preview-2) that we released. The VS 2015 Tooling installer on the main [download page](https://www.microsoft.com/net/core#windows) for .NET Core has also been updated to include this cumulative update. 

@LeeChenelerJS it looks like your issue was because of the security software you had and that is resolved as well. So I'm going ahead and closing this issue.

**Comment by jacodv** [comment]
I cannot install the new preview.  I have tried the "SKIP_VSU_CHECK=1 solution ".  Just gives me a repair option or uninstall option.  Uninstall does nothing, next time I get the repair again.  This is the log


[dd_DotNetCoreTools__20160825131457.zip](https://github.com/aspnet/Tooling/files/436822/dd_DotNetCoreTools__20160825131457.zip)

**Comment by saf-itpro** [comment]
I have the exact same issue as @jacodv described above.

**Comment by Gaby10** [comment]
So do it, and quite often.

**Comment by vitalbsk** [comment]
@LeeChenelerJS LeeChenelerJS thanks. The solution for issue 2 works!
