### ISSUE TITLE
How to add non .net dll reference in project.json.

### ISSUE THREAD

**Issue by rianka** [aspnet/Tooling#719]
please someone tell me how to How to add non .net dll reference in project.json.
All the dlls are added in my project's libs\bin.

**Comment by rianka** [comment]
All the dlls are added in my project's libs\bin.

**Comment by mlorbetske** [comment]
While this will be fixed with the move of .NET Core projects to use csproj projects, you should be able to do this by creating a NuGet package containing the DLL you wish to reference (you can do this with tools like this one http://docs.nuget.org/Create/Using-a-Gui-to-build-packages). Once you've created the package, you'll have to add it to a feed that is available to your project when it restores its dependencies (docs on how to do this are at https://docs.nuget.org/consume/nuget-config-settings). Assuming that your project.json has a framework that is compatible with the framework the DLL is built for, you should be able to add a dependency to that package.
