### ISSUE TITLE
How to disable auto build feature when running under IIS Express

### ISSUE THREAD

**Issue by wanton7** [aspnet/Tooling#762]
After I run my Asp.Net Core application from Visual Studio 2015, it automatically builds project every time I change any .cs file and save it. This is really bad for productivity if you example run lot of build scripts that take some time. Plus it's super annoying and unneeded when you do a big edit to have project build every time you hit CTRL+S.
How to do I disable this "feature"?

**Comment by mlorbetske** [comment]
Unfortunately, there's no way to disable this behavior right now. Could you check to see if you see this same behavior if your site is not open in the browser when you hit save?

**Comment by wanton7** [comment]
Tested it and it's build when there is request from browser. My app is polling data from server every 10 seconds with JQuery Ajax. That's why it's building every time I saved a file.

**Comment by jasselin** [comment]
I would love to have a way to disable this.

**Comment by pacoaw** [comment]
Is there an update on this issue? It's really annoying to have to remember not to press save in visual studio while your working.

**Comment by mlorbetske** [comment]
cc @sayedihashimi

**Comment by pacoaw** [comment]
Microsoft, can you please give us an update on this issue?

**Comment by sayedihashimi** [comment]
@BillHiebert let's discuss after standup today if you have time.

**Comment by qazxsw99** [comment]
When I developing SPA that reply on WebpackDevMiddleware, the nightmare was occurred... Any changes on *.cs will auto trigger build process. Because there is an EventSource connection on web server to wait for any signal for scripting files was changed. If any option to ignore 
 HMR connection so that not to auto compile then it will be great.

**Comment by briman0094** [comment]
I'm having this issue too, exactly as described by the OP. After starting my project in IIS Express (non-debug mode, detached in the background), it will rebuild the project every time I save a `.cs` file. It gets excessively aggravating because not only does it lag for a second when starting the build, but the Error List window (which I normally have minimized) pops up when the build ends if I've saved a file when the project has compilation errors.

This happened to me before installing the SpaServices package, so I don't think it's related to the Webpack development middleware at all.

**Comment by jasselin** [comment]
@sayedihashimi @BillHiebert It's been a year guys, any news? I would love a simple way to disable this "feature".

**Comment by barrytang** [comment]
Thanks for your feedback! We have now added an option for you to turn off this behavior in the upcoming 15.8 update. You can [install the latest preview](https://visualstudio.microsoft.com/vs/preview/) in the meantime if you want.

![image](https://user-images.githubusercontent.com/1648865/43930027-2457cde4-9bec-11e8-967e-00e10c04dcb9.png)

**Comment by Grinderofl** [comment]
This has not been fixed! While a visible rebuild doesn't happen, the server still gets restarted.

**Comment by jasselin** [comment]
Just tried it, same thing here...

**Comment by MilesLin** [comment]
I think this feature should false by default because it changes our default building behavior. Secondly, no one(like me) knows there is an auto-build feature for this specific situation and it causes me very annoying.
