### ISSUE TITLE
Disable dotnet watch within Visual Studio

### ISSUE THREAD

**Issue by muratg** [aspnet/Tooling#793]
_From @jasselin on September 26, 2016 15:58_

Could you provide a way to disable dotnet watch when using Visual Studio?

I have a case where I don't want to rebuild a project when changing any cs files.

Thanks

_Copied from original issue: aspnet/DotNetTools#176_

**Comment by muratg** [comment]
_From @victorhurdugaci on September 26, 2016 16:33_

`dotnet watch` is not enabled in VS. Actually, VS doesn't know at all about `watch`

**Comment by muratg** [comment]
_From @jasselin on September 26, 2016 17:15_

I tought the feature that rebuilds the solution when hitting F5 was dotnet watch.
Do you know any way to disable it? Should I ask the Visual Studio tooling folks?

**Comment by muratg** [comment]
_From @victorhurdugaci on September 26, 2016 17:18_

Nope, that's not `watch`. @troydai or @BillHiebert might know if disabling that is possible. I think it comes from the DTH

**Comment by troydai** [comment]
I'll let @BillHiebert address this issue. But from what know there is nothing related to `dotnet watch` in `Project Model Server` or `DTH`. And actually if the `watch` actually working, it won't be associate with `F5` because all it should deliver is trigger command automatically while files being changed.

**Comment by sayedihashimi** [comment]
If I understand the request correctly the question is: "How can I have my xproj project loaded but not have any action invoked on F5/CTRL + F5". I believe that you can get this behavior by using the Solution Configuration Manager dialog. In that dialog you can see the projects that will be built and you can uncheck the build action for a particular build configuration. After that, for that given build configuration when you F5/CTRL+F5 the project should not be built.
I'll close this now since I believe that we've answered the question. If that's not correct please reopen with more details.

**Comment by jasselin** [comment]
Not really the answer I was looking for, let me explain a little better.

A new feature with ASP.NET Core is the ability to hit "Refresh" in the browser and have Visual Studio rebuild you solution automatically without the need to hit "Ctrl + B" before refreshing the browser. This is great, but I have a special case where I dynamically compile some cs files and I don't want the changes I make to rebuild the whole solution. I get the behavior I want when using the debugger, but Visual Studio 
prevents me from making some changes to my solution while the debugger is running.

I would love to have a way to disable the automatic compilation when refreshing the browser when running my app without having the debugger attached, just like it was before.

I hope this is a little bit more understandable.

**Comment by sayedihashimi** [comment]
>I get the behavior I want when using the debugger, but Visual Studio
prevents me from making some changes to my solution while the debugger is running.

I believe there is a setting for this in tools->options but I'm not 100% sure.

**Comment by jasselin** [comment]
I've looked and can't find it...

**Comment by sayedihashimi** [comment]
>I get the behavior I want when using the debugger, but Visual Studio
prevents me from making some changes to my solution while the debugger is running.

I believe there is a setting for this in tools->options but I'm not 100% sure.
