### ISSUE TITLE
Add option to ignore failed package sources

### ISSUE THREAD

**Issue by danroth27** [aspnet/Tooling#80]
The default runtime behavior for package restore is to fail if a package source fails – package restore should not succeed if you can’t access your configured feeds. However, you can also pass an --ignore-failed-sources option to force a package restore anyway. We need to add a tooling feature that allows you to do the same.

**Comment by sayedihashimi** [comment]
From what I understand ```dnu``` and ```nuget``` will later be merged into one thing. Currently NuGet will restore multiple feeds based on nuget.config. When that merge happens what's going to be the default behavior, is it dnu style and fail if the pkg is not available in the first feed or continue to other feeds?

Also since they will merge, are you asking for us to implement a feature that will later go away? Another possible solution is to add a new attribute/element in nuget.config that can set this value. That way if you have a solution/project that you want to access multiple sources you can create a nuget.config file and then set that attribute/element.

**Comment by sayedihashimi** [comment]
TFS ID: 1137140

**Comment by danroth27** [comment]
DNU will restore from multiple feeds too - that isn't the issue. The issue happens when one of the configured feeds cannot be accessed (ex You are using a MyGet feed and MyGet is down). If any of your configured feeds is not accessible then package restore will fail. We think this is the correct default behavior.

However if you want to force package restore to happen anyway then you can pass on option to tell DNU to ignore failing package sources. We want to have this same option available in tooling.

**Comment by sayedihashimi** [comment]
"The issue happens when one of the configured feeds cannot be accessed (ex You are using a MyGet feed and MyGet is down). If any of your configured feeds is not accessible then package restore will fail. We think this is the correct default behavior."
So NuGet has this behavior as well?

**Comment by danroth27** [comment]
No, NuGet currently has different behavior, but we still think the DNU behavior is correct.

**Comment by sayedihashimi** [comment]
And what about my proposal of adding out to nuget.config. That way it works from the cmd line as well? Then when it gets sorted out with NuGet they can create UI for it.

**Comment by danroth27** [comment]
Let's just wait for the NuGet alignment to get sorted out and then we can make a call on this.

**Comment by sayedihashimi** [comment]
Ok can we close this?

**Comment by danroth27** [comment]
No, the issues still exists and we need to track it.

**Comment by sayedihashimi** [comment]
@danroth27 Ok I've assigned the item to you.

**Comment by mlorbetske** [comment]
This seems related to https://github.com/NuGet/Home/issues/3058. The tooling (especially through the NuGet package manager pane) does a much better job now of indicating the reasons for restore failure & skipping failed feeds can be accomplished by changing the dropdown on that screen. I'll ping the issue on NuGet to see what the recommended procedure for working with these cases when in VS is.
