### ISSUE TITLE
Setting a specific DNX runtime when creating new projects

### ISSUE THREAD

**Issue by leosbrf** [aspnet/Tooling#84]
When creating a new project in Visual Studio 2015 RC (Version 14.0.22823.1 D14REL and .NET Framework 4.6.00057)
1-ASP .NET Web Application (.NET Framework 4.6)
2-Select a template (Website)

Error:

Cannot find the DNX runtime 'dnx-clr-win-x86.1.0.0-beta5-11781'. Please install the runtime using 'dnvm install' command, then close and reopen the solution. For more details about getting the runtime, see https://github.com/aspnet/home.

Is there a way to change the default SDK? Instead of 1.0.0-beta5 I would like VS to use 1.0.0-beta4 by default.

**Comment by sayedihashimi** [comment]
In VS2015 RC when you create a new project the ```default``` alias is used for the value of SDK version inside of the generated ```global.json``` file.

You can modify the value of the ```default``` alias to 1.0.0-beta4 with the command ```dnvm alias default 1.0.0-beta4'

Then when you create a new project that value will be used in ```global.json```.

For existing projects you can modify the SDK value in ```global.json```.

_Note: for the next release of Visual Studio we have decided to move away from the functionality. We will no longer examine the ```default``` alias. Instead when new projects are created the version of dnx shipped with Visual Studio will be used for ```global.json```._

**Comment by sayedihashimi** [comment]
We have changed the design of how this work since my previous comment. In the latest releases when you create a new project it will use the version that is shipped with the VS Web Tools installer. You can change the value of global.json or dependencies in project.json after the project is created.

So when you do File->New Project you should never see that dialog since the dnx is already installed.

I'll close this now.
