### ISSUE TITLE
Consider adding rsync publishing

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Tooling#96]
I just saw #95 and thought to myself: That's something `rsync` has solved for years.

For Linux hosting with SSH connectivity, rsync is probably the most reliable alternative for publishing. I'm currently doing an 
```rsync -a --del app/ user@server:/path/to/app/```
manually from a cygwin command line, which works great.

**Comment by sayedihashimi** [comment]
@Tragetaschen thanks for the comment.

We are currently thinking to use SFTP instead of rsync. I think SFTP may be more ubiquitous versus rsync making it a better option. What do you think about this?

FYI I just created an issue for SFTP support at #98, which includes a walk through. I'd appreciate if you reviewed that and let me know your thoughts.

**Comment by nosami** [comment]
rsync is usually installed by default.... and the speedups can be tremendous compared to a normal file copy.

**Comment by sayedihashimi** [comment]
Thanks @nosami, I will look closer at rsync and maybe come back here with more questions/comments.

**Comment by cce32** [comment]
Another vote for the rsync protocol.  Note it's strength is in trying to only copy the differences between two sets of files.  So no speedup on the initial publish but amazing speedup on subsequent ones.

**Comment by sayedihashimi** [comment]
We are discussing rsync vs sftp at https://github.com/aspnet/Tooling/issues/98. Let's keep the follow up there, I'll close this now.

**Comment by Tragetaschen** [comment]
I'm just watching your [ASP.NET Fall Session](https://channel9.msdn.com/Events/ASPNET-Events/ASPNET-Fall-Sessions/Visual-Studio-Web-Tooling-Futures). Thanks for keeping an eye on rsync :)
